### ISSUE TITLE
Blank Page When Adding Theme To My Wordpress

### ISSUE THREAD

**Issue by kash101** [reduxframework/redux-framework#3365]
Hi,

I dowloaded the Redux Framework using the builder (3.6.5) and generated an underscore theme with it. When I tried to add it to my wordpress (Version 4.8) and clicked on activate theme. My website stopped working and showed me a blank page. I then generated an admin directory from the builder and added it to my other theme, that was working fine, plus added the admin-init.php to my functions.php. Same thing happened.

Am I doing something wrong here? I also tried the plugin method. I downloaded Redux from the plugins and added the sample demo. That worked fine, but when I copied that sample folder to my (Redux Generated) theme, same thing happened. A white blank page everywhere.

**Comment by kprovance** [comment]
Did you read the text provided in the new issue window?  I should close this ticket since none was provided.  Do a Google search for "WordPress Blank Page" and try everything suggested, for what you have is a server issue.  If you search this issue tracker, you will se is typically is.  Review your PHP error logs and check with those to see where the problem is too.  Otherwise, I need the information we asked for.

**Comment by kash101** [comment]
Well, I fixed the issue myself. The problem was in the plugin "admin/admin-init.php on line 22". There is this bit that was causing that issue.

<<<<<<< HEAD
=======
>>>>>>> 697ea2dd8502e5915239f2b886727536ec55fc74

When I removed it to check, everything started to work fine. When I add this, same error happens. I am not sure what to do with this line of code. Any suggestions?

**Comment by kash101** [comment]
Well, I fixed the issue myself. The problem was in the plugin "admin/admin-init.php on line 22". There is this bit that was causing that issue.

#<<<<<<< HEAD
#=======
#>>>>>>> 697ea2dd8502e5915239f2b886727536ec55fc74

When I removed it to check, everything started to work fine. When I add this, same error happens. I am not sure what to do with this line of code. Any suggestions?

**Comment by kprovance** [comment]
Oh boy.  Junk text made it's way into the server.  Great.  @Dovy, you'll have to fix this, as I still do not have access.

**Comment by kprovance** [comment]
Okay, I think I have it fixed now.  That junk should no longer output.
