### ISSUE TITLE
Fatal Error Upon Activation 

### ISSUE THREAD

**Issue by tb7167** [reduxframework/redux-framework#3383]
Hello all, 
   Can anyone possibly provide assistance as to a fix for this fatal error message?

Thank you, 
TB

Fatal error: Uncaught Error: [] operator not supported for strings in /home/minimaltrace1/public_html/us/wp-content/plugins/redux-framework/class.redux-plugin.php:312 Stack trace: #0 /home/minimaltrace1/public_html/us/wp-content/plugins/redux-framework/class.redux-plugin.php(227): ReduxFrameworkPlugin::single_activate() #1 /home/minimaltrace1/public_html/us/wp-includes/class-wp-hook.php(298): ReduxFrameworkPlugin::activate('') #2 /home/minimaltrace1/public_html/us/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters('', Array) #3 /home/minimaltrace1/public_html/us/wp-includes/plugin.php(453): WP_Hook->do_action(Array) #4 /home/minimaltrace1/public_html/us/wp-admin/plugins.php(166): do_action('activate_redux-...') #5 {main} thrown in /home/minimaltrace1/public_html/us/wp-content/plugins/redux-framework/class.redux-plugin.php on line 312

**Comment by kprovance** [comment]
If you are unable to provide the specific information or support hash we require, could you at least provide the Redux version and your PHP version.  If it's 7.1, please go back to the 7.0 version.  There are known issues with 7.1  I don't believe WordPress itself is completely 7.1 stable yet.

**Comment by kprovance** [comment]
I confirmed it to be a PHP 7.1 issue.  You will need to go back to PHP 7.0 until I am able to resolve this.

**Comment by kprovance** [comment]
v.3.6.6.3 should resolve this.  It's available from this repo.

**Comment by spointecker** [comment]
Still having this issue with Redux Version 3.6.7.7 and PHP 7.1

**Comment by kprovance** [comment]
Could you please go back and Supply the required information we ask for we will not be able to help you without it thank you

**Comment by kprovance** [comment]
Never mind, you have piggy backed an old ticket.  We prefer you open a new one.  Please click the New Issue window, READ EVERYTHING PROVIDED, and supply as much as you are able.  The error message or stack trace at the very least.
