### ISSUE TITLE
Critcial Error - Issue New Update

### ISSUE THREAD

**Issue by jmsshiv28** [reduxframework/redux-framework#3743]
[01-Aug-2020 23:03:43 UTC] PHP Warning:  require_once(/home/jmsservi/public_html/wp-content/plugins/redux-framework/redux-core/inc/classes/class-redux-user-feedback.php): failed to open stream: No such file or directory in /home/jmsservi/public_html/wp-content/plugins/redux-framework/redux-core/class-redux-core.php on line 365
[01-Aug-2020 23:03:43 UTC] PHP Fatal error:  require_once(): Failed opening required '/home/jmsservi/public_html/wp-content/plugins/redux-framework/redux-core/inc/classes/class-redux-user-feedback.php' (include_path='.:/opt/alt/php72/usr/share/pear') in /home/jmsservi/public_html/wp-content/plugins/redux-framework/redux-core/class-redux-core.php on line 365

Any quick fix? as im not entirely sure how to go back to the old redux verison which worked fine. Regards

**Comment by dovy** [comment]
Quick fix is to rollback using WP Rollback to 3.8.16. But I would really love access to your instance for 15 mins so I could solve this. I know it would be quick. :)

**Comment by dovy** [comment]
Dovy@redux.io if you’re willing.

**Comment by adventurepro** [comment]
Update Redux and it broke my site and had to restore from backup. I got: 

Fatal error: Uncaught Error: Class 'ReduxFramework_Extension_sortable_extended' not found in /home/customer/www/mysite.com/public_html/wp-content/plugins/redux-framework/redux-core/inc/classes/class-redux-functions-ex.php:307 Stack trace: #0 /home/customer/www/mysite.com/public_html/wp-content/plugins/redux-framework/redux-core/inc/classes/class-redux-api.php(243): Redux_Functions_Ex::extension_compatibility(Object(ReduxFramework), '/home/customer/...', 'ReduxFramework_...', 'ReduxFramework_...', 'sortable') #1 /home/customer/www/mysite.com/public_html/wp-content/plugins/redux-framework/redux-core/inc/classes/class-redux-api.php(208): Redux::load_extensions(Object(ReduxFramework)) #2 /home/customer/www/mysite.com/public_html/wp-includes/class-wp-hook.php(287): Redux::loadExtensions(Object(ReduxFramework)) #3 /home/customer/www/mysite.com/public_html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array) #4 /home/custom in /home/customer/www/mysite.com/public_html/wp-content/plugins/redux-framework/redux-core/inc/classes/class-redux-functions-ex.php on line 307

Any ideas please??

**Comment by dovy** [comment]
Holy cow, that’s frustrating. I’ll get right on it! Can you send me the theme you use so I can test locally? Send via wetransfer.com to dovy@redux.io. 

Whatever you do, don’t update until I let you know it’s ok. :)

**Comment by adventurepro** [comment]
The theme is Alora. Theme4Press

Only seems to affect this theme - all my other sites updated fine.
[alora.zip](https://github.com/reduxframework/redux-framework/files/5012322/alora.zip)

**Comment by jmsshiv28** [comment]
@dovy Sent you an email

**Comment by dovy** [comment]
I believe these problems have been resolved in Redux 4.1.14. Can you please confirm? Sorry for the delay, some of this was quite complex.

**Comment by adventurepro** [comment]
Hi

 

Sorry I still get this after updating – I updated everything else except Redux, then after updating Redux I get:

 

Fatal error: Uncaught Error: Class 'ReduxFramework_Extension_sortable_extended' not found in /home/customer/www/mysite.com/public_html/wp-content/plugins/redux-framework/redux-core/inc/classes/class-redux-functions-ex.php:307 Stack trace: #0 /home/customer/www/mysite.com/public_html/wp-content/plugins/redux-framework/redux-core/inc/classes/class-redux-api.php(243): Redux_Functions_Ex::extension_compatibility(Object(ReduxFramework), '/home/customer/...', 'ReduxFramework_...', 'ReduxFramework_...', 'sortable') #1 /home/customer/www/mysite.com/public_html/wp-content/plugins/redux-framework/redux-core/inc/classes/class-redux-api.php(208): Redux::load_extensions(Object(ReduxFramework)) #2 /home/customer/www/mysite.com/public_html/wp-includes/class-wp-hook.php(287): Redux::loadExtensions(Object(ReduxFramework)) #3 /home/customer/www/mysite.com/public_html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array) #4 /home/custom in /home/customer/www/mysite.com/public_html/wp-content/plugins/redux-framework/redux-core/inc/classes/class-redux-functions-ex.php on line 307

**Comment by adventurepro** [comment]
Hi

Sorry I still get this after updating – I updated everything else except Redux, then after updating Redux I get:

Fatal error: Uncaught Error: Class 'ReduxFramework_Extension_sortable_extended' not found in /home/customer/www/mysite.com/public_html/wp-content/plugins/redux-framework/redux-core/inc/classes/class-redux-functions-ex.php:307 Stack trace: #0 /home/customer/www/mysite.com/public_html/wp-content/plugins/redux-framework/redux-core/inc/classes/class-redux-api.php(243): Redux_Functions_Ex::extension_compatibility(Object(ReduxFramework), '/home/customer/...', 'ReduxFramework_...', 'ReduxFramework_...', 'sortable') #1 /home/customer/www/mysite.com/public_html/wp-content/plugins/redux-framework/redux-core/inc/classes/class-redux-api.php(208): Redux::load_extensions(Object(ReduxFramework)) #2 /home/customer/www/mysite.com/public_html/wp-includes/class-wp-hook.php(287): Redux::loadExtensions(Object(ReduxFramework)) #3 /home/customer/www/mysite.com/public_html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array) #4 /home/custom in /home/customer/www/mysite.com/public_html/wp-content/plugins/redux-framework/redux-core/inc/classes/class-redux-functions-ex.php on line 307

**Comment by dovy** [comment]
I’ll debug alora further then. Thank you for letting me know.

**Comment by dovy** [comment]
This should be fully resolved now. Sorry for the delay!

**Comment by kprovance** [comment]
Hi!

Redux 3.x has reached its end of life.  We will no longer be maintaining it.  Please update to Redux v4, which will be moved to this repository shortly.  Should you should discover the same issue with Redux v4, please rereport the issue, making sure to supply the required information request via the New Issue form.

Thank you for choosing Redux.

- Kev
