### ISSUE TITLE
Redux 4.1.13 JS .replace

### ISSUE THREAD

**Issue by abedshatila** [reduxframework/redux-framework#3745]
So 2 patches back, one of the changes in the change log mentioned a fix in the js .replace issue when there is no opt_name. We actually did a lot of testing and the issue is still there.

You can reproduce it by simply copy pasting the sample config code that you have in your Getting started page in docs.redux

We found a work around that might help you fix the issue. If we dont have any parent section with 1 subsection, the console will show an error. When we add atleast 1 Parent section and 1 subsection, everything will be back to normal.

Hope this sheds some light on the problem

**Comment by dovy** [comment]
So that issue is when people are trying to use a custom typography field. We're working on finding a way for legacy code to work with our new html changes. Hope to solve it forever today.

**Comment by abedshatila** [comment]
No no, not even with a typography field, literally just the field from this page https://docs.redux.io/guides/basics/getting-started.html

If I add a subsection beneath the section from the above link, everything works perfectly fine.

With a brand new theme, in a brand new WordPress installation and no 3rd party plugins.

Good luck solving the issue, and if you need any files from my end to help you reproduce the issue, please I'm more than willing to help.

**Comment by dovy** [comment]
Oh wow, serious?! Send me what you’ve got. Dovy@redux.io. Thank you.

**Comment by abedshatila** [comment]
Ok give me 5 minutes to send you both working and non-working cases in 1 theme.

PS. Backend options are working perfectly fine, its just the customizer

**Comment by dovy** [comment]
Ohhh. That’s really good to know. Thank you.

**Comment by abedshatila** [comment]
Sent. 

Good luck with everything, and thank you for this awesome free plugin, and the even more awesome extensions that you offer.

**Comment by abedshatila** [comment]
Hello Dovy,
Thank you so much for thr efforts you've been putting in the last couple days, must be tough.

Anything new regarding this issue? As a lot of our clients are complaining about the customizer suddenly not working when they updated redux, and this is in like 30+ themes. No pressure, just asking for an update, and thanks

**Comment by dovy** [comment]
I’m trying to get to it, but I have two really critical errors to resolve first. I really appreciate what you’ve provided and I’ll get to it as soon as I am able.

**Comment by dovy** [comment]
Nearing a fix on this. Side note, if you pull from the repo here you'll see the Redux customizer implementation is tons faster. Found a way to really speed up the interactions.

**Comment by abedshatila** [comment]
Music to my ears! Will definitely take a look. And yet again, appreciate the work you're doing! :)

Cheers for the follow up.

**Comment by dovy** [comment]
Good news, just pushed a fix that should resolve it. I haven't pushed to WP.org yet. Please inspect and confirm all is working as you'd hope. Thanks!

**Comment by abedshatila** [comment]
Hi Dovy, I just took a quick look at it, with the same theme that I sent you previously. Seems like the opt name is still missing. I can now see it in the HTML, but JS fails to find it. I'm getting an error on line 1344 redux.optName.folds cannot get folds of undefined.

Like I said, using the same theme I sent previously, with the Working Config, its well, working. and with the config that is missing a subsection, still, no dice.

Let me know If there is anything else I can help with.

**Comment by dovy** [comment]
Weird. I’ll try stepping through again. We’re super close.

**Comment by dovy** [comment]
Fixed! Issue was multiple -'s in the opt_name not being replaced globally. Please verify. The next version is going out today.

**Comment by abedshatila** [comment]
Hey dovy,

Nop still there. I just pulled the latest, and .folds error is still there. Also, tested with the dummy theme I sent you, where the only configuration is the one available from the Getting Started page on redux documentation. Opt name being **redux_demo**

I'm gonna try pulling again just now for the sake of it.

![image](https://user-images.githubusercontent.com/35689007/89931622-1ac89b80-dc15-11ea-8cc0-ae555564d816.png)

**Comment by dovy** [comment]
WEIRD. I'll retry your code. Make sure you don't have another version of Redux running somewhere. Hop on slack sometime.

**Comment by dovy** [comment]
Weird, now I see it. Testing...

**Comment by abedshatila** [comment]
Nop, I have a dedicated WP installation for this case, with only redux plugin and this one theme. Also, pulled again now, and still. I wish I would tell you it got solved.

**Comment by dovy** [comment]
Ha, do another pull. Silly me.

**Comment by dovy** [comment]
Long story short I was using the window's definition of the container, but I needed to use the selector because of a race condition in JS that was causing me to select the pre-added to customizer to get the appropriate opt_name.

Bla bla, that means I made a boo boo. haha.

**Comment by dovy** [comment]
Even more explanation: Redux 3 only allowed for one opt_name to work in the customizer. Redux 4 can now handle any number without conflicts. This error is related to the appropriate opt_name not being selected on load and thus causing a failure.  ;)

**Comment by abedshatila** [comment]
lol **I made a boo boo**. This is as brief as it can get. Give me 2 minutes

**Comment by abedshatila** [comment]
Nop. The images down below, are everything I have.

![image](https://user-images.githubusercontent.com/35689007/89934173-dc34e000-dc18-11ea-864f-b338e8b6cbb5.png)
![image](https://user-images.githubusercontent.com/35689007/89934190-e3f48480-dc18-11ea-96f5-5d8a84a13751.png)
![image](https://user-images.githubusercontent.com/35689007/89934242-f242a080-dc18-11ea-8b2d-8f07770ec95e.png)
![image](https://user-images.githubusercontent.com/35689007/89934271-fec6f900-dc18-11ea-81e8-49c432d3d64e.png)

**Comment by abedshatila** [comment]
I even tried adding opt_name to setSection args, thought maybe that would help. Yea you know what i'm about to say next

**Comment by dovy** [comment]
This is so weird. I'm using your code without any errors or change.

**Comment by abedshatila** [comment]
Correct me if im not mistaken.

I should pull from master yes?
https://github.com/reduxframework/redux-framework-4

**Comment by dovy** [comment]
FSGSIREP_(RUW#. My bad, found it again. I swear I fixed this...

**Comment by abedshatila** [comment]
Code be like:
https://www.youtube.com/watch?v=otCpCn0l4Wo

**Comment by dovy** [comment]
Found it, pull again. For whatever reason: `optName = item.find( '.redux-customizer-opt-name:first-child' ).data( 'opt-name' );` failes if firstchild is there.

**Comment by dovy** [comment]
Makes no sense...

**Comment by dovy** [comment]
(then again a lot of the customizer doesn't make sense to me, haha)

**Comment by abedshatila** [comment]
![image](https://user-images.githubusercontent.com/35689007/89935689-3f277680-dc1b-11ea-87ce-c5ac5ec3d74a.png)

https://www.youtube.com/watch?v=vUN7yu7zvz8

**Comment by abedshatila** [comment]
The video is all I can say.

**Comment by dovy** [comment]
Wahoo!!! Sorry for the delay. This stuff gets crazy complex sometimes.

If you're willing, would you mind leaving a review if you haven't already? https://wordpress.org/support/plugin/redux-framework/reviews/#new-post

I'll have this next version out today. You'll also find the customizer performs loads better.  ;)

**Comment by abedshatila** [comment]
You definitely got my 5 star. Cheers
